SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET NAMES utf8;

CREATE DATABASE IF NOT EXISTS copa_2026;
USE copa_2026;

CREATE TABLE figurinhas (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  numero INT NOT NULL UNIQUE,
  nome VARCHAR(100) NOT NULL,
  idade INT NOT NULL,
  time VARCHAR(100) NOT NULL,
  peso VARCHAR(10),
  selecao VARCHAR(50) NOT NULL,
  posicao VARCHAR(30) NOT NULL,
  data_insercao DATETIME DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

INSERT INTO `figurinhas` (`numero`, `nome`, `idade`, `time`, `peso`, `selecao`, `posicao`) VALUES
-- BRASIL
(1, 'Alisson', 32, 'Liverpool', '91kg', 'Brasil', 'Goleiro'),
(2, 'Ederson', 31, 'Manchester City', '86kg', 'Brasil', 'Goleiro'),
(3, 'Vanderson', 24, 'Monaco', '82kg', 'Brasil', 'Lateral-Direito'),
(4, 'Danilo', 32, 'Juventus', '84kg', 'Brasil', 'Lateral-Direito'),
(5, 'Eder Militao', 25, 'Real Madrid', '86kg', 'Brasil', 'Zagueiro'),
(6, 'Marquinhos', 30, 'Paris Saint-Germain', '88kg', 'Brasil', 'Zagueiro'),
(7, 'Lucas Verissimo', 27, 'Benfica', '85kg', 'Brasil', 'Zagueiro'),
(8, 'Alex Sandro', 32, 'Juventus', '84kg', 'Brasil', 'Lateral-Esquerdo'),
(9, 'Guilherme Arana', 27, 'Atletico Madrid', '78kg', 'Brasil', 'Lateral-Esquerdo'),
(10, 'Casemiro', 32, 'Manchester United', '84kg', 'Brasil', 'Volante'),
(11, 'Joao Gomes', 23, 'Wolverhampton', '80kg', 'Brasil', 'Volante'),
(12, 'Andre', 23, 'Flamengo', '79kg', 'Brasil', 'Volante'),
(13, 'Lucas Paqueta', 26, 'West Ham', '79kg', 'Brasil', 'Meio-Campista'),
(14, 'Rodrygo', 23, 'Real Madrid', '80kg', 'Brasil', 'Extremo'),
(15, 'Vinicius Jr', 24, 'Real Madrid', '76kg', 'Brasil', 'Extremo'),
(16, 'Richarlison', 27, 'Tottenham', '82kg', 'Brasil', 'Ponta'),
(17, 'Gabriel Jesus', 27, 'Arsenal', '75kg', 'Brasil', 'Ponta'),
(18, 'Neymar', 32, 'Al-Hilal', '68kg', 'Brasil', 'Extremo'),

-- ARGENTINA
(19, 'Gonzalo Montiel', 26, 'Nottingham Forest', '80kg', 'Argentina', 'Lateral-Direito'),
(20, 'Juan Diaz', 28, 'Valencia', '82kg', 'Argentina', 'Lateral-Direito'),
(21, 'Nicolas Otamendi', 36, 'Benfica', '84kg', 'Argentina', 'Zagueiro'),
(22, 'Cristian Romero', 26, 'Tottenham', '86kg', 'Argentina', 'Zagueiro'),
(23, 'German Pezzella', 32, 'Betis', '84kg', 'Argentina', 'Zagueiro'),
(24, 'Tagliafico', 31, 'Lyon', '78kg', 'Argentina', 'Lateral-Esquerdo'),
(25, 'Enzo Fernandez', 23, 'Chelsea', '78kg', 'Argentina', 'Volante'),
(26, 'Leandro Paredes', 29, 'AS Roma', '82kg', 'Argentina', 'Volante'),
(27, 'Alexis Mac Allister', 25, 'Brighton', '76kg', 'Argentina', 'Meio-Campista'),
(28, 'Lionel Messi', 39, 'Inter Miami', '72kg', 'Argentina', 'Extremo'),
(29, 'Angel Di Maria', 36, 'Juventus', '74kg', 'Argentina', 'Extremo'),
(30, 'Julian Alvarez', 24, 'Manchester City', '75kg', 'Argentina', 'Ponta'),
(31, 'Lautaro Martinez', 26, 'Inter Milan', '74kg', 'Argentina', 'Ponta'),

-- FRANCA
(32, 'Hugo Lloris', 37, 'Los Angeles FC', '89kg', 'França', 'Goleiro'),
(33, 'Alphonse Areola', 30, 'West Ham', '87kg', 'França', 'Goleiro'),
(34, 'Jules Kounde', 25, 'Barcelona', '82kg', 'França', 'Lateral-Direito'),
(35, 'Achraf Hakimi', 25, 'Paris Saint-Germain', '78kg', 'França', 'Lateral-Direito'),
(36, 'Dayot Upamecano', 26, 'Bayern Munich', '86kg', 'França', 'Zagueiro'),
(37, 'Raphael Varane', 31, 'Manchester United', '82kg', 'França', 'Zagueiro'),
(38, 'Ibrahima Konate', 25, 'Liverpool', '84kg', 'França', 'Zagueiro'),
(39, 'Lucas Hernandez', 28, 'Bayern Munich', '82kg', 'França', 'Lateral-Esquerdo'),
(40, 'Theo Hernandez', 27, 'AC Milan', '81kg', 'França', 'Lateral-Esquerdo'),
(41, 'Aurelien Tchouameni', 24, 'Real Madrid', '80kg', 'França', 'Volante'),
(42, 'Eduardo Camavinga', 21, 'Real Madrid', '78kg', 'França', 'Volante'),
(43, 'N\'Golo Kante', 33, 'Al-Ittihad', '80kg', 'França', 'Volante'),
(44, 'Antoine Griezmann', 33, 'Atletico Madrid', '73kg', 'França', 'Meio-Campista'),
(45, 'Kylian Mbappe', 27, 'Real Madrid', '73kg', 'França', 'Extremo'),
(46, 'Eduardo Messi', 26, 'Barcelona', '79kg', 'França', 'Extremo'),
(47, 'Olivier Giroud', 38, 'AC Milan', '92kg', 'França', 'Ponta'),
(48, 'Matteo Guendouzi', 26, 'Lazio', '77kg', 'França', 'Meio-Campista'),

-- ALEMANHA
(49, 'Manuel Neuer', 38, 'Bayern Munich', '92kg', 'Alemanha', 'Goleiro'),
(50, 'Marc-Andre ter Stegen', 32, 'Barcelona', '87kg', 'Alemanha', 'Goleiro'),
(51, 'Benjamin Pavard', 28, 'Bayern Munich', '85kg', 'Alemanha', 'Lateral-Direito'),
(52, 'Antonio Rudiger', 31, 'Real Madrid', '88kg', 'Alemanha', 'Zagueiro'),
(53, 'Mats Hummels', 35, 'Borussia Dortmund', '89kg', 'Alemanha', 'Zagueiro'),
(54, 'Jonathan Tah', 28, 'Bayer Leverkusen', '86kg', 'Alemanha', 'Zagueiro'),
(55, 'David Raum', 26, 'RB Leipzig', '80kg', 'Alemanha', 'Lateral-Esquerdo'),
(56, 'Jude Bellingham', 21, 'Borussia Dortmund', '75kg', 'Alemanha', 'Volante'),
(57, 'Ilkay Gundogan', 33, 'Manchester City', '76kg', 'Alemanha', 'Volante'),
(58, 'Florian Wirtz', 21, 'Bayer Leverkusen', '78kg', 'Alemanha', 'Extremo'),
(59, 'Jamal Musiala', 21, 'Bayern Munich', '75kg', 'Alemanha', 'Extremo'),
(60, 'Kai Havertz', 25, 'Arsenal', '77kg', 'Alemanha', 'Ponta'),
(61, 'Serge Gnabry', 28, 'Bayern Munich', '81kg', 'Alemanha', 'Extremo'),

-- ESPANHA
(62, 'Unai Simon', 27, 'Athletic Bilbao', '84kg', 'Espanha', 'Goleiro'),
(63, 'Robert Sanchez', 26, 'Chelsea', '86kg', 'Espanha', 'Goleiro'),
(64, 'Juan Miranda', 26, 'Real Betis', '80kg', 'Espanha', 'Lateral-Esquerdo'),
(65, 'Alejandro Balde', 21, 'Barcelona', '76kg', 'Espanha', 'Lateral-Esquerdo'),
(66, 'Cesar Azpilicueta', 34, 'Athletic Bilbao', '82kg', 'Espanha', 'Lateral-Direito'),
(67, 'Dani Carvajal', 32, 'Real Madrid', '81kg', 'Espanha', 'Lateral-Direito'),
(68, 'Sergio Gomez', 21, 'Anderlecht', '77kg', 'Espanha', 'Lateral-Esquerdo'),
(69, 'Pau Torres', 27, 'Villarreal', '85kg', 'Espanha', 'Zagueiro'),
(70, 'Inigo Martinez', 33, 'Athletic Bilbao', '87kg', 'Espanha', 'Zagueiro'),
(71, 'Aymeric Laporte', 30, 'Al-Nassr', '83kg', 'Espanha', 'Zagueiro'),
(72, 'Rodrigo', 29, 'Manchester City', '82kg', 'Espanha', 'Volante'),
(73, 'Sergio Busquets', 35, 'Inter Miami', '79kg', 'Espanha', 'Volante'),
(74, 'Pedri', 21, 'Barcelona', '70kg', 'Espanha', 'Meio-Campista'),
(75, 'Gavi', 20, 'Barcelona', '72kg', 'Espanha', 'Meio-Campista'),
(76, 'Ferran Torres', 26, 'Barcelona', '77kg', 'Espanha', 'Extremo'),
(77, 'Pablo Sarabia', 31, 'Atletico Madrid', '73kg', 'Espanha', 'Extremo'),
(78, 'Alvaro Morata', 32, 'Atletico Madrid', '82kg', 'Espanha', 'Ponta'),

-- INGLATERRA
(79, 'Jordan Pickford', 30, 'Everton', '86kg', 'Inglaterra', 'Goleiro'),
(80, 'Aaron Ramsdale', 26, 'Arsenal', '83kg', 'Inglaterra', 'Goleiro'),
(81, 'Kyle Walker', 34, 'Manchester City', '84kg', 'Inglaterra', 'Lateral-Direito'),
(82, 'Reece James', 24, 'Chelsea', '82kg', 'Inglaterra', 'Lateral-Direito'),
(83, 'Harry Maguire', 31, 'Manchester United', '90kg', 'Inglaterra', 'Zagueiro'),
(84, 'John Stones', 30, 'Manchester City', '81kg', 'Inglaterra', 'Zagueiro'),
(85, 'Luke Shaw', 29, 'Manchester United', '80kg', 'Inglaterra', 'Lateral-Esquerdo'),
(86, 'Bukayo Saka', 23, 'Arsenal', '77kg', 'Inglaterra', 'Lateral-Direito'),
(87, 'Declan Rice', 25, 'Arsenal', '80kg', 'Inglaterra', 'Volante'),
(88, 'Mason Mount', 26, 'Manchester United', '77kg', 'Inglaterra', 'Meio-Campista'),
(89, 'James Maddison', 27, 'Tottenham', '77kg', 'Inglaterra', 'Meio-Campista'),
(90, 'Phil Foden', 26, 'Manchester City', '73kg', 'Inglaterra', 'Extremo'),
(91, 'Jack Grealish', 29, 'Manchester City', '80kg', 'Inglaterra', 'Extremo'),
(92, 'Harry Kane', 32, 'Bayern Munich', '89kg', 'Inglaterra', 'Ponta'),
(93, 'Callum Hudson-Odoi', 24, 'Bayer Leverkusen', '76kg', 'Inglaterra', 'Extremo'),

-- BELGICA
(94, 'Thibaut Courtois', 31, 'Real Madrid', '88kg', 'Bélgica', 'Goleiro'),
(95, 'Simon Mignolet', 36, 'Brugge', '86kg', 'Bélgica', 'Goleiro'),
(96, 'Thomas Meunier', 32, 'Borussia Dortmund', '82kg', 'Bélgica', 'Lateral-Direito'),
(97, 'Achraf Hakimi', 25, 'Paris Saint-Germain', '78kg', 'Bélgica', 'Lateral-Direito'),
(98, 'Jan Vertonghen', 36, 'Anderlecht', '81kg', 'Bélgica', 'Zagueiro'),
(99, 'Axel Witsel', 34, 'Atletico Madrid', '80kg', 'Bélgica', 'Volante'),
(100, 'Kevin De Bruyne', 33, 'Manchester City', '76kg', 'Bélgica', 'Meio-Campista'),
(101, 'Jeremy Doku', 22, 'Manchester City', '75kg', 'Bélgica', 'Extremo'),
(102, 'Eden Hazard', 33, 'Real Madrid', '71kg', 'Bélgica', 'Extremo'),
(103, 'Romelu Lukaku', 31, 'AS Roma', '102kg', 'Bélgica', 'Ponta'),

-- PAISES BAIXOS
(104, 'Marc-Andre ter Stegen', 32, 'Barcelona', '87kg', 'Países Baixos', 'Goleiro'),
(105, 'Jeroen Zoet', 29, 'PSV Eindhoven', '82kg', 'Países Baixos', 'Goleiro'),
(106, 'Denzel Dumfries', 27, 'Inter Milan', '82kg', 'Países Baixos', 'Lateral-Direito'),
(107, 'Nathan Ake', 29, 'Manchester City', '77kg', 'Países Baixos', 'Lateral-Esquerdo'),
(108, 'Virgil van Dijk', 32, 'Liverpool', '88kg', 'Países Baixos', 'Zagueiro'),
(109, 'Stefan de Vrij', 31, 'Lazio', '85kg', 'Países Baixos', 'Zagueiro'),
(110, 'Matthijs de Ligt', 27, 'Bayern Munich', '85kg', 'Países Baixos', 'Zagueiro'),
(111, 'Calvin Stengs', 24, 'AZ Alkmaar', '76kg', 'Países Baixos', 'Extremo'),
(112, 'Frenkie de Jong', 27, 'Barcelona', '73kg', 'Países Baixos', 'Meio-Campista'),
(113, 'Teun Koopmeiners', 26, 'Atalanta', '81kg', 'Países Baixos', 'Meio-Campista'),
(114, 'Memphis Depay', 30, 'PSV Eindhoven', '73kg', 'Países Baixos', 'Ponta'),
(115, 'Wout Weghorst', 31, 'Burnley', '96kg', 'Países Baixos', 'Ponta'),

-- ITALIA
(116, 'Gianluigi Donnarumma', 26, 'Paris Saint-Germain', '84kg', 'Itália', 'Goleiro'),
(117, 'Alex Meret', 27, 'Napoli', '82kg', 'Itália', 'Goleiro'),
(118, 'Giovanni Di Lorenzo', 30, 'Napoli', '80kg', 'Itália', 'Lateral-Direito'),
(119, 'Alessandro Bastoni', 25, 'Inter Milan', '84kg', 'Itália', 'Zagueiro'),
(120, 'Gleison Bremer', 27, 'Juventus', '85kg', 'Itália', 'Zagueiro'),
(121, 'Francesco Acerbi', 35, 'Lazio', '82kg', 'Itália', 'Zagueiro'),
(122, 'Matteo Darmian', 35, 'Inter Milan', '79kg', 'Itália', 'Lateral-Esquerdo'),
(123, 'Nicolo Barella', 27, 'Inter Milan', '80kg', 'Itália', 'Volante'),
(124, 'Marco Verratti', 31, 'Paris Saint-Germain', '68kg', 'Itália', 'Volante'),
(125, 'Matteo Politano', 30, 'Napoli', '72kg', 'Itália', 'Extremo'),
(126, 'Federico Chiesa', 26, 'Juventus', '77kg', 'Itália', 'Extremo'),
(127, 'Ciro Immobile', 36, 'Lazio', '82kg', 'Itália', 'Ponta'),

-- PORTUGAL
(128, 'Jose Sa', 31, 'Wolverhampton', '84kg', 'Portugal', 'Goleiro'),
(129, 'Rui Patricio', 37, 'AS Roma', '83kg', 'Portugal', 'Goleiro'),
(130, 'Diogo Dalot', 25, 'Manchester United', '77kg', 'Portugal', 'Lateral-Direito'),
(131, 'Nelsen Semedo', 29, 'Benfica', '78kg', 'Portugal', 'Lateral-Direito'),
(132, 'Ruben Dias', 26, 'Manchester City', '80kg', 'Portugal', 'Zagueiro'),
(133, 'Antonio Silva', 20, 'Benfica', '82kg', 'Portugal', 'Zagueiro'),
(134, 'Joao Cancelo', 30, 'Manchester City', '76kg', 'Portugal', 'Lateral-Esquerdo'),
(135, 'Nuno Mendes', 22, 'Paris Saint-Germain', '72kg', 'Portugal', 'Lateral-Esquerdo'),
(136, 'Joao Palhinha', 28, 'Fulham', '86kg', 'Portugal', 'Volante'),
(137, 'Rúben Neves', 27, 'Al-Hilal', '80kg', 'Portugal', 'Volante'),
(138, 'Bruno Fernandes', 29, 'Manchester United', '76kg', 'Portugal', 'Meio-Campista'),
(139, 'Cristiano Ronaldo', 39, 'Al-Nassr', '84kg', 'Portugal', 'Ponta'),
(140, 'Goncalo Ramos', 22, 'Benfica', '77kg', 'Portugal', 'Ponta'),

-- DINAMARCA
(141, 'Kasper Schmeichel', 37, 'Anderlecht', '87kg', 'Dinamarca', 'Goleiro'),
(142, 'Peter Vindahl Jensen', 28, 'Las Palmas', '82kg', 'Dinamarca', 'Goleiro'),
(143, 'Rasmus Kristensen', 28, 'Manchester United', '80kg', 'Dinamarca', 'Lateral-Direito'),
(144, 'Romain Faivre', 25, 'Brest', '76kg', 'Dinamarca', 'Extremo'),
(145, 'Jannik Vestergaard', 31, 'Leicester City', '87kg', 'Dinamarca', 'Zagueiro'),
(146, 'Micky van de Ven', 24, 'Tottenham', '85kg', 'Dinamarca', 'Zagueiro'),
(147, 'Christian Eriksen', 32, 'Manchester United', '76kg', 'Dinamarca', 'Meio-Campista'),
(148, 'Yussuf Poulsen', 30, 'RB Leipzig', '85kg', 'Dinamarca', 'Ponta'),
(149, 'Andreas Skov Olsen', 24, 'Bologna', '78kg', 'Dinamarca', 'Extremo'),

-- SUECIA
(150, 'Robin Olsen', 31, 'Aston Villa', '83kg', 'Suécia', 'Goleiro'),
(151, 'Isak Bergstrom', 29, 'Malmö', '82kg', 'Suécia', 'Goleiro'),
(152, 'Mikael Lustig', 37, 'Helsingborg', '79kg', 'Suécia', 'Lateral-Direito'),
(153, 'Mattias Svanberg', 25, 'Bologna', '78kg', 'Suécia', 'Volante'),
(154, 'Viktor Lindelof', 30, 'Manchester United', '85kg', 'Suécia', 'Zagueiro'),
(155, 'Pontus Jansson', 32, 'Brentford', '88kg', 'Suécia', 'Zagueiro'),
(156, 'Emil Krafth', 28, 'Newcastle United', '80kg', 'Suécia', 'Lateral-Direito'),
(157, 'Dejan Kulusevski', 27, 'Tottenham', '77kg', 'Suécia', 'Extremo'),
(158, 'Sebastian Larsson', 38, 'AZ Alkmaar', '76kg', 'Suécia', 'Extremo'),
(159, 'Alexander Isak', 25, 'Newcastle United', '78kg', 'Suécia', 'Ponta'),

-- POLAND
(160, 'Wojciech Szczesny', 34, 'Juventus', '84kg', 'Polônia', 'Goleiro'),
(161, 'Lukasz Skorupski', 32, 'Bologna', '83kg', 'Polônia', 'Goleiro'),
(162, 'Matty Cash', 26, 'Aston Villa', '81kg', 'Polônia', 'Lateral-Direito'),
(163, 'Jan Bednarek', 28, 'Aston Villa', '84kg', 'Polônia', 'Zagueiro'),
(164, 'Jakub Kiwior', 24, 'Arsenal', '80kg', 'Polônia', 'Lateral-Esquerdo'),
(165, 'Grzegorz Krychowiak', 34, 'Al-Shabab', '84kg', 'Polônia', 'Volante'),
(166, 'Piotr Zielinski', 30, 'Napoli', '73kg', 'Polônia', 'Meio-Campista'),
(167, 'Arkadiusz Milik', 30, 'Juventus', '82kg', 'Polônia', 'Ponta'),
(168, 'Robert Lewandowski', 36, 'Barcelona', '81kg', 'Polônia', 'Ponta'),

-- MEXICO
(169, 'Alfredo Talavera', 42, 'Juarez', '82kg', 'México', 'Goleiro'),
(170, 'Guillermo Ochoa', 38, 'AVV', '83kg', 'México', 'Goleiro'),
(171, 'Jorge Sanchez', 26, 'Ajax', '76kg', 'México', 'Lateral-Direito'),
(172, 'Néstor Araujo', 32, 'Tribet Bhoys', '84kg', 'México', 'Zagueiro'),
(173, 'Hector Moreno', 35, 'Monterrey', '82kg', 'México', 'Zagueiro'),
(174, 'Jesus Gallardo', 28, 'Betis', '74kg', 'México', 'Lateral-Esquerdo'),
(175, 'Edson Alvarez', 25, 'West Ham', '79kg', 'México', 'Volante'),
(176, 'Hector Herrera', 33, 'Houston Dynamo', '78kg', 'México', 'Volante'),
(177, 'Jesus Manuel Corona', 31, 'Sevilla', '75kg', 'México', 'Extremo'),
(178, 'Santiago Gimenez', 23, 'Feyenoord', '76kg', 'México', 'Ponta'),
(179, 'Hirving Lozano', 28, 'Napoli', '70kg', 'México', 'Extremo'),

-- CANADA
(180, 'Milan Borjan', 32, 'Red Star Belgrade', '83kg', 'Canadá', 'Goleiro'),
(181, 'Dayne St. Clair', 27, 'Minnesota United', '82kg', 'Canadá', 'Goleiro'),
(182, 'Achraf Hakimi', 25, 'Paris Saint-Germain', '78kg', 'Canadá', 'Lateral-Direito'),
(183, 'Doneil Henry', 31, 'Toronto FC', '84kg', 'Canadá', 'Zagueiro'),
(184, 'Steven Vitoria', 27, 'Braga', '86kg', 'Canadá', 'Zagueiro'),
(185, 'Richie Laryea', 28, 'Toronto FC', '77kg', 'Canadá', 'Lateral-Direito'),
(186, 'Alphonso Davies', 24, 'Bayern Munich', '72kg', 'Canadá', 'Lateral-Esquerdo'),
(187, 'Athanasios Rantos', 27, 'Toronto FC', '76kg', 'Canadá', 'Volante'),
(188, 'Mark-Anthony Kaye', 29, 'Los Angeles FC', '78kg', 'Canadá', 'Volante'),
(189, 'Jonathan David', 25, 'Lille', '77kg', 'Canadá', 'Ponta'),
(190, 'Cyle Larin', 29, 'Besiktas', '76kg', 'Canadá', 'Ponta'),

-- USA
(191, 'Matt Turner', 29, 'Nottingham Forest', '82kg', 'Estados Unidos', 'Goleiro'),
(192, 'Ethan Horvath', 28, 'Nottingham Forest', '84kg', 'Estados Unidos', 'Goleiro'),
(193, 'Sergiño Dest', 24, 'Barcelona', '73kg', 'Estados Unidos', 'Lateral-Esquerdo'),
(194, 'Joe Scally', 26, 'Borussia Mönchengladbach', '78kg', 'Estados Unidos', 'Lateral-Direito'),
(195, 'Folau Kalamafoni', 23, 'Tottenham', '81kg', 'Estados Unidos', 'Zagueiro'),
(196, 'Cameron Carter-Vickers', 25, 'Celtic', '84kg', 'Estados Unidos', 'Zagueiro'),
(197, 'Antonee Robinson', 25, 'Fulham', '76kg', 'Estados Unidos', 'Lateral-Direito'),
(198, 'Tyler Adams', 29, 'AFC Bournemouth', '80kg', 'Estados Unidos', 'Volante'),
(199, 'Yunus Musah', 25, 'Valencia', '75kg', 'Estados Unidos', 'Volante'),
(200, 'Weston McKennie', 26, 'Juventus', '82kg', 'Estados Unidos', 'Meio-Campista'),
(201, 'Gio Reyna', 25, 'Borussia Dortmund', '75kg', 'Estados Unidos', 'Extremo'),
(202, 'Folarin Balogun', 23, 'Arsenal', '74kg', 'Estados Unidos', 'Ponta'),
(203, 'Sergen Orsus', 24, 'Al Hilal', '76kg', 'Estados Unidos', 'Extremo'),

-- JAPAO
(204, 'Shuichi Gonda', 32, 'Urawa Red Diamonds', '83kg', 'Japão', 'Goleiro'),
(205, 'Eiji Kawashima', 39, 'Strasbourg', '82kg', 'Japão', 'Goleiro'),
(206, 'Hiroki Sakai', 33, 'Urawa Red Diamonds', '79kg', 'Japão', 'Lateral-Direito'),
(207, 'Yuto Nagatomo', 36, 'Firenze Viola', '76kg', 'Japão', 'Lateral-Esquerdo'),
(208, 'Ryoji Morisaki', 24, 'AZ Alkmaar', '78kg', 'Japão', 'Zagueiro'),
(209, 'Yuki Abe', 34, 'Urawa Red Diamonds', '81kg', 'Japão', 'Zagueiro'),
(210, 'Takehiro Tomiyasu', 24, 'Arsenal', '81kg', 'Japão', 'Lateral-Direito'),
(211, 'Wataru Endo', 30, 'Stuttgart', '76kg', 'Japão', 'Volante'),
(212, 'Hidemasa Morita', 26, 'Sporting CP', '74kg', 'Japão', 'Volante'),
(213, 'Takumi Minamino', 29, 'Monaco', '71kg', 'Japão', 'Extremo'),
(214, 'Kaoru Mitoma', 25, 'Brighton', '73kg', 'Japão', 'Extremo'),
(215, 'Daichi Kamada', 27, 'Eintracht Frankfurt', '76kg', 'Japão', 'Extremo'),
(216, 'Shinji Okazaki', 36, 'Huracán', '77kg', 'Japão', 'Ponta'),

-- COREIA DO SUL
(217, 'Kim Seung-gyu', 30, 'Al-Wehda', '83kg', 'Coreia do Sul', 'Goleiro'),
(218, 'Jo Hyeon-woo', 29, 'Ulsan Hyundai', '81kg', 'Coreia do Sul', 'Goleiro'),
(219, 'Kim Min-jae', 27, 'Napoli', '84kg', 'Coreia do Sul', 'Zagueiro'),
(220, 'Lim Young-yun', 28, 'Shanghai Port', '82kg', 'Coreia do Sul', 'Zagueiro'),
(221, 'Hong Chul', 33, 'Daegu FC', '80kg', 'Coreia do Sul', 'Lateral-Direito'),
(222, 'Kim Jin-su', 31, 'Al-Shabab', '78kg', 'Coreia do Sul', 'Lateral-Esquerdo'),
(223, 'Lee Kang-in', 22, 'Paris Saint-Germain', '69kg', 'Coreia do Sul', 'Extremo'),
(224, 'Jung Woo-young', 24, 'Hamburgo', '77kg', 'Coreia do Sul', 'Volante'),
(225, 'Kang-in Lee', 22, 'Paris Saint-Germain', '69kg', 'Coreia do Sul', 'Meio-Campista'),
(226, 'Son Heung-min', 31, 'Tottenham', '77kg', 'Coreia do Sul', 'Extremo'),
(227, 'Hwang Hee-chan', 28, 'Wolverhampton', '80kg', 'Coreia do Sul', 'Ponta'),
(228, 'Oh Se-hun', 24, 'Ulsan Hyundai', '74kg', 'Coreia do Sul', 'Extremo'),

-- AUSTRALIA
(229, 'Andrew Redmayne', 33, 'Sydney FC', '83kg', 'Austrália', 'Goleiro'),
(230, 'Mathew Ryan', 32, 'AZ Alkmaar', '82kg', 'Austrália', 'Goleiro'),
(231, 'Aziz Behich', 32, 'Dundee United', '80kg', 'Austrália', 'Lateral-Esquerdo'),
(232, 'Thomas Deng', 22, 'Newcastle United', '76kg', 'Austrália', 'Lateral-Direito'),
(233, 'Bailey Wright', 31, 'Sunderland', '84kg', 'Austrália', 'Zagueiro'),
(234, 'Trent Sainsbury', 33, 'Perth Glory', '85kg', 'Austrália', 'Zagueiro'),
(235, 'Harry Souttar', 25, 'Leicester City', '86kg', 'Austrália', 'Zagueiro'),
(236, 'Nathaniel Atkinson', 26, 'Hearts', '78kg', 'Austrália', 'Lateral-Direito'),
(237, 'Jackson Irvine', 31, 'Hull City', '79kg', 'Austrália', 'Volante'),
(238, 'Denis Genreau', 24, 'Parma', '71kg', 'Austrália', 'Extremo'),
(239, 'Awer Mabil', 27, 'Cadiz', '74kg', 'Austrália', 'Extremo'),
(240, 'Martin Boyle', 28, 'Hibernian', '73kg', 'Austrália', 'Extremo'),

-- MARROCOS
(241, 'Bono', 31, 'Al-Wehda', '83kg', 'Marrocos', 'Goleiro'),
(242, 'Ahmed Reda Tagnaouti', 28, 'Wydad Casablanca', '82kg', 'Marrocos', 'Goleiro'),
(243, 'Achraf Hakimi', 25, 'Paris Saint-Germain', '78kg', 'Marrocos', 'Lateral-Direito'),
(244, 'Noussair Mazraoui', 27, 'Bayern Munich', '81kg', 'Marrocos', 'Lateral-Direito'),
(245, 'Romain Faivre', 25, 'Brest', '76kg', 'Marrocos', 'Extremo'),
(246, 'Romain Saïss', 32, 'Besiktas', '82kg', 'Marrocos', 'Volante'),
(247, 'Sofyan Amrabat', 27, 'Fiorentina', '78kg', 'Marrocos', 'Volante'),
(248, 'Youssef En-Nesyri', 26, 'Sevilla', '78kg', 'Marrocos', 'Ponta'),
(249, 'Hakim Ziyech', 30, 'Galatasaray', '74kg', 'Marrocos', 'Extremo'),

-- TUQUIA
(250, 'Altay Bayindir', 24, 'Manchester United', '82kg', 'Turquia', 'Goleiro'),
(251, 'Ugurcan Cakir', 26, 'Trabzonspor', '84kg', 'Turquia', 'Goleiro'),
(252, 'Mert Gunok', 35, 'Besiktas', '83kg', 'Turquia', 'Goleiro'),
(253, 'Zeki Celik', 25, 'Roma', '79kg', 'Turquia', 'Lateral-Direito'),
(254, 'Merih Demiral', 27, 'Al-Wehda', '85kg', 'Turquia', 'Zagueiro'),
(255, 'Ozan Kabak', 24, 'Norwich City', '82kg', 'Turquia', 'Zagueiro'),
(256, 'Kaan Ayhan', 28, 'Sassuolo', '81kg', 'Turquia', 'Zagueiro'),
(257, 'Ridvan Yilmaz', 23, 'Rangers', '77kg', 'Turquia', 'Lateral-Esquerdo'),
(258, 'Emre Can', 29, 'Borussia Dortmund', '84kg', 'Turquia', 'Volante'),
(259, 'Hakan Calhanoglu', 29, 'Inter Milan', '75kg', 'Turquia', 'Meio-Campista'),
(260, 'Burak Yilmaz', 37, 'Adana Demirspor', '85kg', 'Turquia', 'Ponta'),
(261, 'Serdar Dursun', 30, 'Fenerbahce', '84kg', 'Turquia', 'Ponta'),

-- EGITO
(262, 'Mahmoud El-Wensh', 31, 'Zamalek', '84kg', 'Egito', 'Goleiro'),
(263, 'Mohamed El-Shenawy', 33, 'Al-Ahly', '82kg', 'Egito', 'Goleiro'),
(264, 'Ahmed Elmohamady', 35, 'Aston Villa', '81kg', 'Egito', 'Lateral-Direito'),
(265, 'Mohamed Salah', 32, 'Liverpool', '75kg', 'Egito', 'Extremo'),
(266, 'Amr El-Sulaya', 32, 'Al-Zamalek', '79kg', 'Egito', 'Zagueiro'),
(267, 'Emam Ashour', 26, 'Al-Ahly', '80kg', 'Egito', 'Zagueiro'),
(268, 'Omar Gaber', 25, 'Zamalek', '76kg', 'Egito', 'Lateral-Esquerdo'),
(269, 'Tarek Hamed', 31, 'Al-Zamalek', '78kg', 'Egito', 'Volante'),
(270, 'Mohamed Elneny', 31, 'Arsenal', '77kg', 'Egito', 'Volante'),

-- SENEGAL
(272, 'Edouard Mendy', 32, 'Al-Ahly', '85kg', 'Senegal', 'Goleiro'),
(273, 'Seny Dieng', 28, 'Lens', '86kg', 'Senegal', 'Goleiro'),
(274, 'Saliou Ciss', 28, 'Besiktas', '81kg', 'Senegal', 'Lateral-Direito'),
(275, 'Youssouf Sabaly', 29, 'Real Betis', '80kg', 'Senegal', 'Lateral-Direito'),
(276, 'Kalidou Koulibaly', 31, 'Al-Hilal', '88kg', 'Senegal', 'Zagueiro'),
(277, 'Abdou Diallo', 27, 'RB Leipzig', '82kg', 'Senegal', 'Zagueiro'),
(278, 'Cheikhou Kouyate', 32, 'Nottingham Forest', '84kg', 'Senegal', 'Volante'),
(279, 'Idrissa Gueye', 33, 'Everton', '80kg', 'Senegal', 'Volante'),
(280, 'Pape Gueye', 25, 'Olympique Marseille', '78kg', 'Senegal', 'Volante'),
(281, 'Ismaila Sarr', 25, 'Watford', '75kg', 'Senegal', 'Extremo'),
(282, 'Sadio Mane', 31, 'Al-Nassr', '73kg', 'Senegal', 'Ponta'),
(283, 'Boulaye Dia', 26, 'Salernitana', '78kg', 'Senegal', 'Ponta'),

-- GANA
(284, 'Wontumi Hor', 25, 'Asante Kotoko', '81kg', 'Gana', 'Goleiro'),
(285, 'Lawrence Ati-Zigi', 27, 'St. Gallen', '83kg', 'Gana', 'Goleiro'),
(286, 'Jeremie Frimpong', 23, 'Bayer Leverkusen', '77kg', 'Gana', 'Lateral-Direito'),
(287, 'Seidu Bukari', 24, 'Lazio', '76kg', 'Gana', 'Lateral-Esquerdo'),
(288, 'Daniel Amartey', 28, 'Leicester City', '85kg', 'Gana', 'Zagueiro'),
(289, 'Kofi Korsah', 23, 'Gent', '82kg', 'Gana', 'Zagueiro'),
(290, 'Alexander Djiku', 27, 'Strasbourg', '84kg', 'Gana', 'Zagueiro'),
(291, 'Tarique Fosu', 25, 'Charlton Athletic', '76kg', 'Gana', 'Extremo'),
(292, 'Mohammed Kudus', 23, 'Ajax', '78kg', 'Gana', 'Meio-Campista'),
(293, 'Andre Ayew', 34, 'Al-Sadd', '76kg', 'Gana', 'Extremo'),
(294, 'Thomas Partey', 30, 'Arsenal', '74kg', 'Gana', 'Volante'),
(295, 'Jordan Ayew', 33, 'Crystal Palace', '74kg', 'Gana', 'Ponta'),

-- NIGERIA
(296, 'Francis Uzoho', 25, 'Omonia Nicosia', '82kg', 'Nigéria', 'Goleiro'),
(297, 'Daniel Okoye', 30, 'Enyimba', '84kg', 'Nigéria', 'Goleiro'),
(298, 'Tariq Lamptey', 22, 'Brighton', '72kg', 'Nigéria', 'Lateral-Direito'),
(299, 'Ola Aina', 26, 'Torino', '77kg', 'Nigéria', 'Lateral-Esquerdo'),
(300, 'William Troost-Ekong', 29, 'Watford', '85kg', 'Nigéria', 'Zagueiro'),
(301, 'Jamilu Collins', 27, 'Pafos', '84kg', 'Nigéria', 'Lateral-Esquerdo'),
(302, 'Joe Aribo', 26, 'Southampton', '73kg', 'Nigéria', 'Extremo'),
(303, 'Wilfred Ndidi', 26, 'Leicester City', '79kg', 'Nigéria', 'Volante'),
(304, 'Iwobi Alex', 27, 'Fulham', '76kg', 'Nigéria', 'Extremo'),
(305, 'Victor Osimhen', 25, 'Napoli', '77kg', 'Nigéria', 'Ponta'),

-- CAMERUN
(306, 'Fabrice Ondoa', 27, 'Nantes', '82kg', 'Camarões', 'Goleiro'),
(307, 'Andre Onana', 27, 'Inter Milan', '85kg', 'Camarões', 'Goleiro'),
(308, 'Achraf Hakimi', 25, 'Paris Saint-Germain', '78kg', 'Camarões', 'Lateral-Direito'),
(309, 'Nouhou Tolo', 25, 'Seattle Sounders', '80kg', 'Camarões', 'Lateral-Esquerdo'),
(310, 'Samuel Eto\'o Jr', 28, 'Royal Antwerp', '81kg', 'Camarões', 'Lateral-Direito'),
(311, 'Collins Fai', 27, 'Al-Wehda', '80kg', 'Camarões', 'Lateral-Direito'),
(312, 'Jerome Ngom Mbekeli', 28, 'Auxerre', '82kg', 'Camarões', 'Zagueiro'),
(313, 'Jean-Charles Castelletto', 27, 'Nantes', '84kg', 'Camarões', 'Zagueiro'),
(314, 'Andre Zambo Anguissa', 26, 'Napoli', '77kg', 'Camarões', 'Volante'),
(315, 'Madji Biouele', 26, 'Salernitana', '75kg', 'Camarões', 'Volante'),
(316, 'Pierre Kunde Malong', 32, 'Nantes', '82kg', 'Camarões', 'Volante'),
(317, 'Vincent Aboubakar', 32, 'Al-Fayha', '87kg', 'Camarões', 'Ponta'),
(318, 'Stéphane Bahoken', 28, 'Angers', '79kg', 'Camarões', 'Ponta');
